// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlugin = "plugin"

// Plugin mapped from table <plugin>
type Plugin struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PluginID      string    `gorm:"column:plugin_id;not null;default:0" json:"plugin_id"`
	PluginName    string    `gorm:"column:plugin_name;not null" json:"plugin_name"`
	LatestVersion string    `gorm:"column:latest_version;not null" json:"latest_version"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Plugin's table name
func (*Plugin) TableName() string {
	return TableNamePlugin
}
