// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plugin/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create Plugin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreatePlugin"
                ],
                "summary": "CreatePlugin",
                "operationId": "CreatePlugin",
                "parameters": [
                    {
                        "description": "Create Plugin",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/index.Plugin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete Plugin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeletePlugin"
                ],
                "summary": "DeletePlugin",
                "operationId": "DeletePlugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin_Name",
                        "name": "plugin_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Plugin Version",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List Plugin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListPlugin"
                ],
                "summary": "ListPlugin",
                "operationId": "ListPlugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin Name",
                        "name": "plugin_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Plugin Version",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/listall": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List Plugin ALL Version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListPluginAllVersion"
                ],
                "summary": "ListPluginAllVersion",
                "operationId": "ListPluginAllVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin Name",
                        "name": "plugin_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Search Plugin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SearchPlugin"
                ],
                "summary": "SearchPlugin",
                "operationId": "SearchPlugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin Name",
                        "name": "plugin_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Plugin Version",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/searchall": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Search Plugin ALL Version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SearchPluginAllVersion"
                ],
                "summary": "SearchPluginAllVersion",
                "operationId": "SearchPluginAllVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin Name",
                        "name": "plugin_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/plugin/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update Plugin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UpdatePlugin"
                ],
                "summary": "UpdatePlugin",
                "operationId": "UpdatePlugin",
                "parameters": [
                    {
                        "description": "Update Plugin",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/index.Plugin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "List User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListUser"
                ],
                "summary": "ListUser",
                "operationId": "ListUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserName",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "get": {
                "description": "User Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Login",
                "operationId": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserName",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PassWord",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegisterUser"
                ],
                "summary": "RegisterUser",
                "operationId": "RegisterUser",
                "parameters": [
                    {
                        "description": "Register User",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/verifytoken": {
            "get": {
                "description": "Verify Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VerifyToken"
                ],
                "summary": "VerifyToken",
                "operationId": "VerifyToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "index.FileOperation": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "index.Platform": {
            "type": "object",
            "properties": {
                "bin": {
                    "description": "Bin specifies the path to the plugin executable.\nThe path is relative to the root of the installation folder.\nThe binary will be linked after all FileOperations are executed.",
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/index.FileOperation"
                    }
                },
                "selector": {
                    "$ref": "#/definitions/v1.LabelSelector"
                },
                "sha256": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "index.Plugin": {
            "type": "object",
            "properties": {
                "annotations": {
                    "description": "Annotations is an unstructured key value map stored with a resource that may be\nset by external tools to store and retrieve arbitrary metadata. They are not\nqueryable and should be preserved when modifying objects.\nMore info: http://kubernetes.io/docs/user-guide/annotations\n+optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "apiVersion": {
                    "description": "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources\n+optional",
                    "type": "string"
                },
                "creationTimestamp": {
                    "description": "CreationTimestamp is a timestamp representing the server time when this object was\ncreated. It is not guaranteed to be set in happens-before order across separate operations.\nClients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system.\nRead-only.\nNull for lists.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata\n+optional",
                    "type": "string"
                },
                "deletionGracePeriodSeconds": {
                    "description": "Number of seconds allowed for this object to gracefully terminate before\nit will be removed from the system. Only set when deletionTimestamp is also set.\nMay only be shortened.\nRead-only.\n+optional",
                    "type": "integer"
                },
                "deletionTimestamp": {
                    "description": "DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This\nfield is set by the server when a graceful deletion is requested by the user, and is not\ndirectly settable by a client. The resource is expected to be deleted (no longer visible\nfrom resource lists, and not reachable by name) after the time in this field, once the\nfinalizers list is empty. As long as the finalizers list contains items, deletion is blocked.\nOnce the deletionTimestamp is set, this value may not be unset or be set further into the\nfuture, although it may be shortened or the resource may be deleted prior to this time.\nFor example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react\nby sending a graceful termination signal to the containers in the pod. After that 30 seconds,\nthe Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup,\nremove the pod from the API. In the presence of network partitions, this object may still\nexist after this timestamp, until an administrator or automated process can determine the\nresource is fully terminated.\nIf not set, graceful deletion of the object has not been requested.\n\nPopulated by the system when a graceful deletion is requested.\nRead-only.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata\n+optional",
                    "type": "string"
                },
                "finalizers": {
                    "description": "Must be empty before the object is deleted from the registry. Each entry\nis an identifier for the responsible component that will remove the entry\nfrom the list. If the deletionTimestamp of the object is non-nil, entries\nin this list can only be removed.\nFinalizers may be processed and removed in any order.  Order is NOT enforced\nbecause it introduces significant risk of stuck finalizers.\nfinalizers is a shared field, any actor with permission can reorder it.\nIf the finalizer list is processed in order, then this can lead to a situation\nin which the component responsible for the first finalizer in the list is\nwaiting for a signal (field value, external system, or other) produced by a\ncomponent responsible for a finalizer later in the list, resulting in a deadlock.\nWithout enforced ordering finalizers are free to order amongst themselves and\nare not vulnerable to ordering changes in the list.\n+optional\n+patchStrategy=merge",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "generateName": {
                    "description": "GenerateName is an optional prefix, used by the server, to generate a unique\nname ONLY IF the Name field has not been provided.\nIf this field is used, the name returned to the client will be different\nthan the name passed. This value will also be combined with a unique suffix.\nThe provided value has the same validation rules as the Name field,\nand may be truncated by the length of the suffix required to make the value\nunique on the server.\n\nIf this field is specified and the generated name exists, the server will return a 409.\n\nApplied only if Name is not specified.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency\n+optional",
                    "type": "string"
                },
                "generation": {
                    "description": "A sequence number representing a specific generation of the desired state.\nPopulated by the system. Read-only.\n+optional",
                    "type": "integer"
                },
                "kind": {
                    "description": "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\n+optional",
                    "type": "string"
                },
                "labels": {
                    "description": "Map of string keys and values that can be used to organize and categorize\n(scope and select) objects. May match selectors of replication controllers\nand services.\nMore info: http://kubernetes.io/docs/user-guide/labels\n+optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "managedFields": {
                    "description": "ManagedFields maps workflow-id and version to the set of fields\nthat are managed by that workflow. This is mostly for internal\nhousekeeping, and users typically shouldn't need to set or\nunderstand this field. A workflow can be the user's name, a\ncontroller's name, or the name of a specific apply path like\n\"ci-cd\". The set of fields is always in the version that the\nworkflow used when modifying the object.\n\n+optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ManagedFieldsEntry"
                    }
                },
                "name": {
                    "description": "Name must be unique within a namespace. Is required when creating resources, although\nsome resources may allow a client to request the generation of an appropriate name\nautomatically. Name is primarily intended for creation idempotence and configuration\ndefinition.\nCannot be updated.\nMore info: http://kubernetes.io/docs/user-guide/identifiers#names\n+optional",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace defines the space within which each name must be unique. An empty namespace is\nequivalent to the \"default\" namespace, but \"default\" is the canonical representation.\nNot all objects are required to be scoped to a namespace - the value of this field for\nthose objects will be empty.\n\nMust be a DNS_LABEL.\nCannot be updated.\nMore info: http://kubernetes.io/docs/user-guide/namespaces\n+optional",
                    "type": "string"
                },
                "ownerReferences": {
                    "description": "List of objects depended by this object. If ALL objects in the list have\nbeen deleted, this object will be garbage collected. If this object is managed by a controller,\nthen an entry in this list will point to this controller, with the controller field set to true.\nThere cannot be more than one managing controller.\n+optional\n+patchMergeKey=uid\n+patchStrategy=merge",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.OwnerReference"
                    }
                },
                "resourceVersion": {
                    "description": "An opaque value that represents the internal version of this object that can\nbe used by clients to determine when objects have changed. May be used for optimistic\nconcurrency, change detection, and the watch operation on a resource or set of resources.\nClients must treat these values as opaque and passed unmodified back to the server.\nThey may only be valid for a particular resource or set of resources.\n\nPopulated by the system.\nRead-only.\nValue must be treated as opaque by clients and .\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency\n+optional",
                    "type": "string"
                },
                "selfLink": {
                    "description": "Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.\n+optional",
                    "type": "string"
                },
                "spec": {
                    "$ref": "#/definitions/index.PluginSpec"
                },
                "uid": {
                    "description": "UID is the unique in time and space value for this object. It is typically generated by\nthe server on successful creation of a resource and is not allowed to change on PUT\noperations.\n\nPopulated by the system.\nRead-only.\nMore info: http://kubernetes.io/docs/user-guide/identifiers#uids\n+optional",
                    "type": "string"
                }
            }
        },
        "index.PluginSpec": {
            "type": "object",
            "properties": {
                "caveats": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "homepage": {
                    "type": "string"
                },
                "platforms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/index.Platform"
                    }
                },
                "shortDescription": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserRequestBody": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "util.Res": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.FieldsV1": {
            "type": "object"
        },
        "v1.LabelSelector": {
            "type": "object",
            "properties": {
                "matchExpressions": {
                    "description": "matchExpressions is a list of label selector requirements. The requirements are ANDed.\n+optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.LabelSelectorRequirement"
                    }
                },
                "matchLabels": {
                    "description": "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is \"key\", the\noperator is \"In\", and the values array contains only \"value\". The requirements are ANDed.\n+optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.LabelSelectorRequirement": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "key is the label key that the selector applies to.\n+patchMergeKey=key\n+patchStrategy=merge",
                    "type": "string"
                },
                "operator": {
                    "description": "operator represents a key's relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist.",
                    "type": "string"
                },
                "values": {
                    "description": "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch.\n+optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.ManagedFieldsEntry": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "description": "APIVersion defines the version of this resource that this field set\napplies to. The format is \"group/version\" just like the top-level\nAPIVersion field. It is necessary to track the version of a field\nset because it cannot be automatically converted.",
                    "type": "string"
                },
                "fieldsType": {
                    "description": "FieldsType is the discriminator for the different fields format and version.\nThere is currently only one possible value: \"FieldsV1\"",
                    "type": "string"
                },
                "fieldsV1": {
                    "description": "FieldsV1 holds the first JSON version format as described in the \"FieldsV1\" type.\n+optional",
                    "$ref": "#/definitions/v1.FieldsV1"
                },
                "manager": {
                    "description": "Manager is an identifier of the workflow managing these fields.",
                    "type": "string"
                },
                "operation": {
                    "description": "Operation is the type of operation which lead to this ManagedFieldsEntry being created.\nThe only valid values for this field are 'Apply' and 'Update'.",
                    "type": "string"
                },
                "subresource": {
                    "description": "Subresource is the name of the subresource used to update that object, or\nempty string if the object was updated through the main resource. The\nvalue of this field is used to distinguish between managers, even if they\nshare the same name. For example, a status update will be distinct from a\nregular update using the same manager name.\nNote that the APIVersion field is not related to the Subresource field and\nit always corresponds to the version of the main resource.",
                    "type": "string"
                },
                "time": {
                    "description": "Time is the timestamp of when the ManagedFields entry was added. The\ntimestamp will also be updated if a field is added, the manager\nchanges any of the owned fields value or removes a field. The\ntimestamp does not update when a field is removed from the entry\nbecause another manager took it over.\n+optional",
                    "type": "string"
                }
            }
        },
        "v1.OwnerReference": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "description": "API version of the referent.",
                    "type": "string"
                },
                "blockOwnerDeletion": {
                    "description": "If true, AND if the owner has the \"foregroundDeletion\" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs \"delete\" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.\n+optional",
                    "type": "boolean"
                },
                "controller": {
                    "description": "If true, this reference points to the managing controller.\n+optional",
                    "type": "boolean"
                },
                "kind": {
                    "description": "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the referent.\nMore info: http://kubernetes.io/docs/user-guide/identifiers#names",
                    "type": "string"
                },
                "uid": {
                    "description": "UID of the referent.\nMore info: http://kubernetes.io/docs/user-guide/identifiers#uids",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
