GOENV: DEV
SREW_SERVER__DB_DSN: root:a8EyHxVuaZeS9J@tcp(127.0.0.1:3306)/cluster_mgr?charset=utf8mb4&parseTime=True&loc=Local
SREW_SERVER__Server_LogFormatter: json
SREW_SERVER__Server_LogLevel: debug
SREW_SERVER__Server_Mode: debug
SREW_SERVER__TestEnvStr: global.config
